### ISSUE TITLE
请求失败：https://websv.aliyundrive.com/token/refresh

### ISSUE THREAD

**Issue by zwt-zf** [zxbu/webdav-aliyundriver#129]
2021-11-06 22:53:36.619 ERROR 6857 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aliYunDriverCronTask': Unsatisfied dependency expressed through field 'aliYunDriverClientService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aliYunDriverClientService' defined in URL [jar:file:/Users/tiger.zhang/Tools/webdav-aliyundriver-2.4.2.jar!/BOOT-INF/classes!/com/github/zxbu/webdavteambition/store/AliYunDriverClientService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/zxbu/webdavteambition/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: 请求失败：https://websv.aliyundrive.com/token/refresh
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1415) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.2.jar!/:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar!/:5.3.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.1.jar!/:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.1.jar!/:2.4.1]
	at com.github.zxbu.webdavteambition.WebdavTeambitionApplication.main(WebdavTeambitionApplication.java:21) [classes!/:2.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_302]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [webdav-aliyundriver-2.4.2.jar:2.4.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [webdav-aliyundriver-2.4.2.jar:2.4.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [webdav-aliyundriver-2.4.2.jar:2.4.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [webdav-aliyundriver-2.4.2.jar:2.4.0]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aliYunDriverClientService' defined in URL [jar:file:/Users/tiger.zhang/Tools/webdav-aliyundriver-2.4.2.jar!/BOOT-INF/classes!/com/github/zxbu/webdavteambition/store/AliYunDriverClientService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/zxbu/webdavteambition/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: 请求失败：https://websv.aliyundrive.com/token/refresh
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1206) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1367) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.2.jar!/:5.3.2]
	... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/zxbu/webdavteambition/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: 请求失败：https://websv.aliyundrive.com/token/refresh
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1367) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.2.jar!/:5.3.2]
	... 41 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: 请求失败：https://websv.aliyundrive.com/token/refresh
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.2.jar!/:5.3.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.2.jar!/:5.3.2]
	... 55 common frames omitted
Caused by: net.sf.webdav.exceptions.WebdavException: 请求失败：https://websv.aliyundrive.com/token/refresh
	at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYunDriverClient.java:152) ~[classes!/:2.4.0]
	at com.github.zxbu.webdavteambition.client.AliYunDriverClient$1.authenticate(AliYunDriverClient.java:53) ~[classes!/:2.4.0]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:230) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:119) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
	at com.github.zxbu.webdavteambition.client.AliYunDriverClient$2.intercept(AliYunDriverClient.java:41) ~[classes!/:2.4.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar!/:na]
	at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYunDriverClient.java:148) ~[classes!/:2.4.0]
	at com.github.zxbu.webdavteambition.client.AliYunDriverClient.init(AliYunDriverClient.java:85) ~[classes!/:2.4.0]
	at com.github.zxbu.webdavteambition.client.AliYunDriverClient.<init>(AliYunDriverClient.java:75) ~[classes!/:2.4.0]
	at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig.teambitionClient(AliYunDriverAutoConfig.java:22) ~[classes!/:2.4.0]
	at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig$$EnhancerBySpringCGLIB$$4d45f612.CGLIB$teambitionClient$0(<generated>) ~[classes!/:2.4.0]
	at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig$$EnhancerBySpringCGLIB$$4d45f612$$FastClassBySpringCGLIB$$a5233854.invoke(<generated>) ~[classes!/:2.4.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.2.jar!/:5.3.2]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.2.jar!/:5.3.2]
	at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig$$EnhancerBySpringCGLIB$$4d45f612.teambitionClient(<generated>) ~[classes!/:2.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_302]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.2.jar!/:5.3.2]
	... 56 common frames omitted

**Comment by MingGH** [comment]
+1，同样的问题

**Comment by eamonzzz** [comment]
+1

**Comment by AlleNPooh** [comment]
+1

**Comment by ghostry** [comment]
c.g.z.w.client.AliYunDriverClient        : 请求失败，url=https://websv.aliyundrive.com/token/refresh, code=429, body=

我的在这种错误之前有一个这个，感觉是重要信息。429好像是请求次数过多

**Comment by MingGH** [comment]
各位，之前这个问题我解决了，忘记跟你们说了。
就是在网页上进行退出，然后重新登录进行获取新的refresh_token, 等待一会儿时间，再进行配置试试
实测，请求阿里云接口就是可以的了
![image](https://user-images.githubusercontent.com/32670399/141139541-3dbf807a-9187-43bc-886f-fbf2b4aceb2b.png)

**Comment by zwt-zf** [comment]
> 各位，之前这个问题我解决了，忘记跟你们说了。 就是在网页上删除localStorage进行退出，然后重新登录进行获取新的refresh_token, 等待一会儿时间，再进行配置试试 实测，请求阿里云接口就是可以的了 ![image](https://user-images.githubusercontent.com/32670399/141140098-00e98b18-5c9a-47ba-9127-7a690b227a9e.png)
> 
> ![image](https://user-images.githubusercontent.com/32670399/141139541-3dbf807a-9187-43bc-886f-fbf2b4aceb2b.png)

赞！好使了~
