### ISSUE TITLE
在arm环境下，用jar包运行服务，无法使用。

### ISSUE THREAD

**Issue by doeasier** [zxbu/webdav-aliyundriver#175]
在arm环境下，用jar包运行服务，无法使用。环境是一台群晖DS416，没有docker环境，于是在终端中用尝试用jar运行。
启动过程中有几条错误，提示文件无法写缓存

2022-02-23 13:21:01.099  INFO 2058 --- [           main] c.g.z.w.WebdavTeambitionApplication      : Starting WebdavTeambitionApplication v2.4.0 using Java 11.0.12 on cxj-nas with PID 2058 (/volume1/homes/nasadmin/aliddns/webdav-aliyundriver-2.4.2.jar started by nasadmin in /volume1/homes/nasadmin/aliddns)
2022-02-23 13:21:01.396  INFO 2058 --- [           main] c.g.z.w.WebdavTeambitionApplication      : No active profile set, falling back to default profiles: default
2022-02-23 13:23:20.169  INFO 2058 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6318 (http)
2022-02-23 13:23:21.625  INFO 2058 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-02-23 13:23:21.635  INFO 2058 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.41]
**2022-02-23 13:23:23.837  WARN 2058 --- [           main] org.apache.catalina.webresources.Cache   : Unable to add the resource at [/META-INF/MANIFEST.MF] to the cache for web application [] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
2022-02-23 13:23:23.855  WARN 2058 --- [           main] org.apache.catalina.webresources.Cache   : Unable to add the resource at [/WEB-INF/classes/META-INF/MANIFEST.MF] to the cache for web application [{1}] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
2022-02-23 13:23:24.320  WARN 2058 --- [           main] org.apache.catalina.webresources.Cache   : Unable to add the resource at [/WEB-INF/classes] to the cache for web application [{1}] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache**
2022-02-23 13:23:26.564  INFO 2058 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-02-23 13:23:26.570  INFO 2058 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 137538 ms
2022-02-23 13:24:03.839  INFO 2058 --- [           main] c.g.z.w.client.AliYunDriverClient        : post https://websv.aliyundrive.com/token/refresh, body {"refresh_token":"b5173bba97594c60b50be20aeaed7052"}, code 200
2022-02-23 13:24:06.561  INFO 2058 --- [           main] c.g.z.w.client.AliYunDriverClient        : post /user/get, body {}, code 200
2022-02-23 13:24:33.345  INFO 2058 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-02-23 13:24:48.040  WARN 2058 --- [           main] org.apache.catalina.webresources.Cache   : Unable to add the resource at [/index.html] to the cache for web application [] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
2022-02-23 13:24:57.441  INFO 2058 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2022-02-23 13:24:59.986  INFO 2058 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6318 (http) with context path ''
2022-02-23 13:25:01.877  INFO 2058 --- [           main] c.g.z.w.WebdavTeambitionApplication      : Started WebdavTeambitionApplication in 296.181 seconds (JVM running for 323.843)

当有客户端连接时，提示 null的错误，不知道是不是初始时的错误引起的，错误如下：
2022-02-23 13:27:35.101 ERROR 2058 --- [nio-6318-exec-1] o.a.c.c.C.[.[.[/].[webdavServlet]        : Servlet.service() for servlet [webdavServlet] threw exception

java.lang.NullPointerException: null
	at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:218) ~[na:na]
	at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:426) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:411) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.http11.Http11OutputBuffer.sendHeader(Http11OutputBuffer.java:371) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1005) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:379) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.Response.action(Response.java:211) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.Response.sendHeaders(Response.java:437) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:291) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:272) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:500) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at net.sf.webdav.WebDavServletBean.returnError(WebDavServletBean.java:194) ~[classes!/:2.4.0]
	at net.sf.webdav.WebDavServletBean.service(WebDavServletBean.java:112) ~[classes!/:2.4.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.41.jar!/:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.2.jar!/:5.3.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:398) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:257) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:179) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-02-23 13:27:35.174 ERROR 2058 --- [nio-6318-exec-1] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

**Comment by ErDongChen1973** [comment]
我Armv7l用jar可以用，就是CPU占用有点儿高
