### ISSUE TITLE
Linux mount 之后 CP 命令报错

### ISSUE THREAD

**Issue by expoli** [zxbu/webdav-aliyundriver#22]
- mount
```
sudo mount.davfs http://127.0.0.1:10080 ./google_photos/ -o rw,uid=1000
```

- 报错信息
```
cannot create regular file './takeout-20210718T040659Z-001.tgz': Input/output error
```
- davfs2 版本
```
extra/davfs2 1.6.0-1
```
- webdav-aliyundriver 版本：基于最新主分支构建

**Comment by zxbu** [comment]
看一下服务端日志，并发出来

**Comment by expoli** [comment]
- 客户端报错
```log
Google 相册/Photos from 2016/IMG_20160828_150501.jpg
        131.07K   5%    1.74kB/s    0:21:07  rsync: [receiver] mkstemp "/data/1TB/tmp/AutoUploads/Google_Photos/Google \#347\#233\#270\#345\#206\#214/Photos from 2016/.IMG_20160828_150458.jpg.json.tdY3Pg" failed: Input/output error (5)
rsync: [receiver] mkstemp "/data/1TB/tmp/AutoUploads/Google_Photos/Google \#347\#233\#270\#345\#206\#214/Photos from 2016/.IMG_20160828_150501.jpg.8eSYye" failed: Input/output error (5)
          2.33M 100%   30.59kB/s    0:01:14 (xfr#7, ir-chk=4406/6608)
Google 相册/Photos from 2016/IMG_20160828_150501.jpg.json
            860 100%    1.15kB/s    0:00:00 (xfr#8, ir-chk=4405/6608)
Google 相册/Photos from 2016/IMG_20160828_155338.jpg
         32.77K   1%   42.16kB/s    0:00:39  ^C

```
- 服务端报错
```log
2021-07-22 16:08:52.000  INFO 1 --- [nio-8080-exec-7] c.g.z.w.client.AliYunDriverClient        : post /file/list, body {"marker":"WyI2MGYzZmRkZGVjM.....=","limit":100,"order_by":"updated_at","order_direction":"DESC","drive_id":"2386986","all":false,"fields":"*","image_thumbnail_process":"image/resize,w_400/format,jpeg","image_url_process":"image/resize,w_1920/format,jpeg","parent_file_id":"60f3fdddec0e69703b684a96b069f0ce8....","video_thumbnail_process":"video/snapshot,t_0,f_jpg,ar_auto,w_300"}, code 200
2021-07-22 16:08:52.659  INFO 1 --- [nio-8080-exec-7] c.g.z.w.client.AliYunDriverClient        : post /file/list, body {"marker":"WyI2MGYzZmRkZGVjM.....=","limit":100,"order_by":"updated_at","order_direction":"DESC","drive_id":"2386986","all":false,"fields":"*","image_thumbnail_process":"image/resize,w_400/format,jpeg","image_url_process":"image/resize,w_1920/format,jpeg","parent_file_id":"60f3fdddec0e69703b684a96b069f0ce8....","video_thumbnail_process":"video/snapshot,t_0,f_jpg,ar_auto,w_300"}, code 200
2021-07-22 16:08:52.791  INFO 1 --- [nio-8080-exec-7] c.g.z.w.s.AliYunDriverFileSystemStore    : createResource /AutoUploads/Google_Photos/Google 相册/Photos from 2016/.IMG_20160828_150501.jpg.8eSYye

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)

2021-07-22 16:08:53.626  INFO 1 --- [nio-8080-exec-8] c.g.z.w.client.AliYunDriverClient        : post /file/list, body {"marker":null,"limit":100,"order_by":"updated_at","order_direction":"DESC","drive_id":"2386986","all":false,"fields":"*","image_thumbnail_process":"image/resize,w_400/format,jpeg","image_url_process":"image/resize,w_1920/format,jpeg","parent_file_id":"root","video_thumbnail_process":"video/snapshot,t_0,f_jpg,ar_auto,w_300"}, code 200
2021-07-22 16:08:53.695  INFO 1 --- [nio-8080-exec-8] c.g.z.w.client.AliYunDriverClient        : post /file/list, body {"marker":null,"limit":100,"order_by":"updated_at","order_direction":"DESC","drive_id":"2386986","all":false,"fields":"*","image_thumbnail_process":"image/resize,w_400/format,jpeg","image_url_process":"image/resize,w_1920/format,jpeg","parent_file_id":"60f3a7e6ced1909ba0f64458ad4cd6ba74....","video_thumbnail_process":"video/snapshot,t_0,f_jpg,ar_auto,w_300"}, code 200
2021-07-22 16:08:53.761  INFO 1 --- [nio-8080-exec-8] c.g.z.w.client.AliYunDriverClient        : post /file/list, body {"marker":null,"limit":100,"order_by":"updated_at","order_direction":"DESC","drive_id":"2386986","all":false,"fields":"*","image_thumbnail_process":"image/resize,w_400/format,jpeg","image_url_process":"image/resize,w_1920/format,jpeg","parent_file_id":"60f3ef5a0caac7b5f0974b8dafb2645593....","video_thumbnail_process":"video/snapshot,t_0,f_jpg,ar_auto,w_300"}, code 200
```

**Comment by zxbu** [comment]
这个错误日志感觉不是很全，是不是省了部分信息？ 看不出来
另外，建议你用rclone挂载本地磁盘，应该更稳定些

**Comment by expoli** [comment]
好的 后续尝试一下 rclone

**Comment by expoli** [comment]
> 这个错误日志感觉不是很全，是不是省了部分信息？ 看不出来
> 另外，建议你用rclone挂载本地磁盘，应该更稳定些

测试了一下 rclone 没有什么问题、应该是 Linux davfs2  的问题

**Comment by zxbu** [comment]
davfs 客户端也应该修复了，你试试最新版本
