### ISSUE TITLE
用 Termux（Android）运行失败

### ISSUE THREAD

**Issue by Gokou-Ruri** [zxbu/webdav-aliyundriver#80]
同样的命令在PC端成功运行且挂载webdav成功，但在Android端碰到了问题。

`java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
`
系统是Android 11类原生，机型为红米k20pro。
```
java -jar webdav-2.4.1.jar --aliyundrive.refresh-token="已删除" --server.port="8080" --aliyundrive.auth.enable=true --aliyundrive.auth.user-name="alibb" --aliyundrive.auth.password="bbali"

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.1)

2021-09-05 01:40:21.541  INFO 9998 --- [           main] c.g.z.w.WebdavTeambitionApplication      : Starting WebdavTeambitionApplication v2.4.0 using Java 1.8.0_152 on localhost with PID 9998 (/home/java/webdav-2.4.1.jar started by ? in /home/java)
2021-09-05 01:40:21.547  INFO 9998 --- [           main] c.g.z.w.WebdavTeambitionApplication      : No active profile set, falling back to default profiles: default
2021-09-05 01:40:23.994  INFO 9998 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-09-05 01:40:24.028  INFO 9998 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-09-05 01:40:24.029  INFO 9998 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.41]
2021-09-05 01:40:24.147  INFO 9998 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-09-05 01:40:24.147  INFO 9998 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2460 ms
2021-09-05 01:40:24.797  WARN 9998 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aliYunDriverClientService' defined in URL [jar:file:/home/java/webdav-2.4.1.jar!/BOOT-INF/classes!/com/github/zxbu/webdavteambition/store/AliYunDriverClientService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/zxbu/webdavteambition/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: java.net.UnknownHostException: api.aliyundrive.com: Name or service not known
2021-09-05 01:40:24.804  INFO 9998 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-09-05 01:40:24.830  INFO 9998 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-09-05 01:40:24.894 ERROR 9998 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'aliYunDriverClientService' defined in URL [jar:file:/home/java/webdav-2.4.1.jar!/BOOT-INF/classes!/com/github/zxbu/webdavteambition/store/AliYunDriverClientService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/zxbu/webdavteambition/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: java.net.UnknownHostException: api.aliyundrive.com: Name or service not known
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1206) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.2.jar!/:5.3.2]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar!/:5.3.2]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar!/:2.4.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [spring-boot-2.4.1.jar!/:2.4.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.1.jar!/:2.4.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.1.jar!/:2.4.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.1.jar!/:2.4.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.1.jar!/:2.4.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.1.jar!/:2.4.1]
        at com.github.zxbu.webdavteambition.WebdavTeambitionApplication.main(WebdavTeambitionApplication.java:19) [classes!/:2.4.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [webdav-2.4.1.jar:2.4.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [webdav-2.4.1.jar:2.4.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [webdav-2.4.1.jar:2.4.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [webdav-2.4.1.jar:2.4.0]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/zxbu/webdavteambition/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: java.net.UnknownHostException: api.aliyundrive.com: Name or service not known
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1367) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.2.jar!/:5.3.2]
        ... 28 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.zxbu.webdavteambition.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: java.net.UnknownHostException: api.aliyundrive.com: Name or service not known
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.2.jar!/:5.3.2]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.2.jar!/:5.3.2]
        ... 42 common frames omitted
Caused by: net.sf.webdav.exceptions.WebdavException: java.net.UnknownHostException: api.aliyundrive.com: Name or service not known
        at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYunDriverClient.java:156) ~[classes!/:2.4.0]
        at com.github.zxbu.webdavteambition.client.AliYunDriverClient.init(AliYunDriverClient.java:85) ~[classes!/:2.4.0]
        at com.github.zxbu.webdavteambition.client.AliYunDriverClient.<init>(AliYunDriverClient.java:75) ~[classes!/:2.4.0]
        at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig.teambitionClient(AliYunDriverAutoConfig.java:22) ~[classes!/:2.4.0]
        at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig$$EnhancerBySpringCGLIB$$57442902.CGLIB$teambitionClient$0(<generated>) ~[classes!/:2.4.0]
        at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig$$EnhancerBySpringCGLIB$$57442902$$FastClassBySpringCGLIB$$c0664b1d.invoke(<generated>) ~[classes!/:2.4.0]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.2.jar!/:5.3.2]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.2.jar!/:5.3.2]
        at com.github.zxbu.webdavteambition.config.AliYunDriverAutoConfig$$EnhancerBySpringCGLIB$$57442902.teambitionClient(<generated>) ~[classes!/:2.4.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.2.jar!/:5.3.2]
        ... 43 common frames omitted
Caused by: java.net.UnknownHostException: api.aliyundrive.com: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_152]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_152]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_152]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_152]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_152]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_152]
        at okhttp3.Dns.lambda$static$0(Dns.java:39) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
        at com.github.zxbu.webdavteambition.client.AliYunDriverClient$2.intercept(AliYunDriverClient.java:41) ~[classes!/:2.4.0]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar!/:na]
        at com.github.zxbu.webdavteambition.client.AliYunDriverClient.post(AliYunDriverClient.java:148) ~[classes!/:2.4.0]
        ... 56 common frames omitted
```

**Comment by Gokou-Ruri** [comment]
问题解决，换官方源的openjdk17就行了。
