### ISSUE TITLE
上传文件后刷新文件夹没有任何数据显示

### ISSUE THREAD

**Issue by QiuYukang** [zxbu/webdav-aliyundriver#88]
使用RaiDrive将阿里云盘挂载到了本地磁盘，将本地硬盘的文件拷贝到挂载的阿里云磁盘后显示上传成功，但是在文件夹里看不到文件（阿里云盘网页版/APP中可以看到新上传的文件，webdav-2.4.1.jar日志显示也能请求到文件列表）

使用的软件版本
- webdav-2.4.1.jar
- RaiDrive 2021.5.20
- win10

日志显示如下：
```bash
2021-09-09 23:49:36.762  INFO 15592 --- [http-nio-8088-exec-2] c.g.z.w.s.AliYunDriverFileSystemStore    : getResourceLength: /xxx/yyy/zzz/云南虫谷12.mp4
2021-09-09 23:49:36.762  INFO 15592 --- [http-nio-8088-exec-2] c.g.z.w.s.AliYunDriverFileSystemStore    : getStoredObject: /xxx/yyy/zzz/云南虫谷/秒传_1080P高码.1~7_13.7GB_2021/0903/09:32.txt
2021-09-09 23:49:36.762 ERROR 15592 --- [http-nio-8088-exec-2] net.sf.webdav.WebDavServletBean          : Exception: java.lang.NullPointerException
	at net.sf.webdav.methods.DoPropfind.parseProperties(DoPropfind.java:256)
	at net.sf.webdav.methods.DoPropfind.recursiveParseProperties(DoPropfind.java:212)
	at net.sf.webdav.methods.DoPropfind.recursiveParseProperties(DoPropfind.java:227)
	at net.sf.webdav.methods.DoPropfind.execute(DoPropfind.java:165)
	at net.sf.webdav.WebDavServletBean.service(WebDavServletBean.java:131)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.zxbu.webdavteambition.filter.ErrorFilter.doFilterInternal(ErrorFilter.java:39)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

2021-09-09 23:49:48.858  INFO 15592 --- [http-nio-8088-exec-4] c.g.z.w.s.AliYunDriverFileSystemStore    : getStoredObject: /
2021-09-09 23:49:48.858  INFO 15592 --- [http-nio-8088-exec-4] c.g.z.w.s.AliYunDriverFileSystemStore    : getResourceLength: /
2021-09-09 23:49:48.859  INFO 15592 --- [http-nio-8088-exec-4] c.g.z.w.s.AliYunDriverFileSystemStore    : getStoredObject: /
```

**Comment by zxbu** [comment]
文件名不要带/
